# Simple install with
# mamba env create -f environment.yml
name: simlearner3d
channels:
  - pytorch
  - nvidia
  - comet_ml
  - conda-forge
dependencies:
  - python=3.9.*
  - pip
  # --------- Deep Learning --------- #
  - pytorch::pytorch=2.1
  - pytorch::pytorch-cuda=11.8
  - pytorch::torchvision=0.16
  - conda-forge::lightning=2.0
  - conda-forge::torchmetrics=0.11
  - conda-forge::scikit-learn=1.5.2
  # Troubleshooting: if libcusparse.so.11. errors occur, run
  # export LD_LIBRARY_PATH="/home/${USER}/miniconda/envs/lib:$LD_LIBRARY_PATH"
  # ou
  # export LD_LIBRARY_PATH="/home/${USER}/anaconda3/envs/lib:$LD_LIBRARY_PATH"
  # see https://github.com/pyg-team/pytorch_geometric/issues/2040#issuecomment-766610625
  # --------- data formats --------- #
  - numpy==1.26.4
  - h5py
  # --------- geo --------- #
  - pdal==2.6.*
  - python-pdal
  - conda-forge:gdal
  - conda_forge:pyproj
  # --------- Visualization --------- #
  - pandas
  - matplotlib
  # --------- loggers --------- #
  - comet_ml::comet_ml=3.35
  - conda-forge::urllib3<2 # To solve for https://github.com/GeneralMills/pytrends/issues/591
    # --------- Visualization --------- #
  - pandas
  - matplotlib
  - seaborn # used in some callbacks
  # --------- linters --------- #
  - pre-commit # hooks for applying linters on commit
  - black # code formatting
  - isort # import sorting
  - flake8 # code analysis
  # --------- tests --------- #
  - pytest==7.1.*
  - coverage==6.3.*
  - pytest-cov==3.0.*
  # --------- others --------- #
  - python-dotenv # loading env variables from .env file
  - rich # beautiful text formatting in terminal
  #- sh # for running bash commands in some tests
  - pudb # debugger
  - twine # to publish pip package
    # # --------- Documentation --------- #
  - sphinx==4.5.*
  - recommonmark==0.7.*
  - sphinx_rtd_theme==1.0.*
  - docutils==0.17
  - rstcheck==3.3.* # RST Linter
  - pip:
      - tifffile
      - rasterio>=1.3.8
      - hydra-core==1.1.*
      - hydra-colorlog==1.1.*
      - protobuf>=4.24.3
      - google-auth>=2.23.0
      - google-auth-oauthlib>=1.0.0
      - imageio>=2.31.3
      - tensorboard>=2.14.0
      - tensorboard-data-server>=0.7.1
      #- kiwisolver>=1.4.7
      - kornia>=0.7.0
      # --------- Documentation --------- #
      - myst_parser==0.17.*
      - sphinxnotes-mock==1.0.0b0 # still a beta
      - sphinx_paramlinks==0.5.*
      - ign-pdal-tools>=1.5.2
