[project]
name = "simlearner3d"
dynamic = ["version"]
description = "Learning similarity for 3D reconstruction from aerial and satellite imagery"
readme = "README.md"
authors = [
    { name = "Mohamed Ali Chebbi", email = "mohamed-ali.chebbi@ign.fr" }
]
maintainers = [
  {name = "Mohamed Ali Chebbi", email = "mohamed-ali.chebbi@ign.fr"}
]

dependencies = []  # assume an environment as described in environment.yml

[metadata]
project_template = "https://github.com/ashleve/lightning-hydra-template"

[project.urls]
Documentation = "https://dalichebbi.github.io/simlearner3d/"
Repository = "https://github.com/DaliCHEBBI/simlearner3d"
Issues = "https://github.com/DaliCHEBBI/simlearner3d/issues"
Changelog = "https://github.com/DaliCHEBBI/simlearner3d/blob/master/CHANGELOG.md"

[tool.setuptools.dynamic]
version = {attr = "simlearner3d._version.__version__"}

[tool.setuptools]
packages = [ "simlearner3d" ]

[tool.black]
line-length = 99
target-version = ['py39']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''

[tool.isort]
profile="black"
src_paths="simlearner3d,test"

[tool.pytest.ini_options]
log_cli = true
testpaths = [
    "tests/simlearner3d/",
]
# Add coverage
addopts = "--cov ./simlearner3d/ --cov-report html --cov-fail-under 75 --cov-config pyproject.toml"

filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning"
]

markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')"
]

[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true