defaults:
  - default.yaml
  - override criterion: BinaryEntropyLoss.yaml


lr: 0.003933709606504788   # 200-long LR-test-range betw 10^-4 and 3.0

neural_net_class_name: "UNetGatedAttention"
neural_net_hparams:
  in_channels: 1
  init_features: 32


mode: "feature+decision"