# https://www.comet.ml

comet:
  _target_: pytorch_lightning.loggers.comet.CometLogger
  save_dir: '.' # should be specified
  #api_key: ${oc.env:COMET_API_TOKEN} # api key is laoded from environment variable
  workspace: ${oc.env:COMET_WORKSPACE}
  project_name: ${oc.env:COMET_PROJECT_NAME}
  experiment_name: "MSAFF_COS_ONLY" # can be overrided at runtime
  auto_log_co2: false
  disabled: false
