prepare_dataset:
  left: /home/MAChebbi/opt/simlearner3d/tests/left2.txt
  right: /home/MAChebbi/opt/simlearner3d/tests/right2.txt
  disp: /home/MAChebbi/opt/simlearner3d/tests/disp2.txt
  masq: /home/MAChebbi/opt/simlearner3d/tests/masq2.txt
  out_dir: /home/MAChebbi/opt/simlearner3d/tests/Stereo
data_split:
  train: 90 
  val: 5
  test: 5