version_name: MSAFF_SENTINEL_DEFORM_2D
device: cuda
n_workers: 16
n_gpus: 1
dim: 2
logger:
  log_files_every_n_iter: 1000
  log_scalars_every_n_iter: 100
  log_validation_every_n_epochs: 1
image:
  image_res: &image_res 7 # (height, width)
feature:
  e: &feature_e 64 # encoding size
dataset:
  name: SENTINEL
  path_train: '/home/mohamedali/Documents/1.Travaux/61.GeneralizedLearning/train'
  path_val: 'home/mohamedali/Documents/1.Travaux/61.GeneralizedLearning/test'
  path_gt: '/home/ad/alichem/scratch/stereo_test/Data/PairwiseSTEREO/Train-Track2-RGB-Val-GT/Track2-Truth'
  use_single: 0 
train:
  epochs: 100
  bs: 16
  num_workers : 16
  accumulate_grad_batches: 1
  seed: 41127
val:
  bs: 16
  num_workers : 16
  seed: 41127
test:
  bs: 1
  num_workers : 10
  seed: 41127
