python run.py task.task_name="finetune" \
datamodule.hdf5_file_path="/home/MAChebbi/opt/simlearner3d/Salon.hdf5" \
datamodule.masq_divider=255 \
datamodule.patch_size=512 \
datamodule.batch_size=2 \
datamodule.sign_disp_multiplier=1 \
experiment="PSMNETDebug" \
trainer.accelerator="cpu" \
++trainer.accumulate_grad_batches=4 \
++trainer.precision="16-mixed" \
model="psmnet" \
++model.load_pretrained=true \
+model.ckpt_path="/home/MAChebbi/opt/simlearner3d/simlearner3d/models/PSMNet/models/trained_assets/finetune_PSMnet.tar" \
++model.channel=3 \
logger=tensorboard 
#++logger.comet.experiment_name="test_psmnet_normalization_finetune_sat"

#++model.load_pretrained=true \
#+model.ckpt_path="/home/MAChebbi/repositories/simlearner3d/simlearner3d/models/PSMNet/models/trained_assets/finetune_PSMnet.tar" \
