python run.py task.task_name="fit" \
datamodule.hdf5_file_path="/home/MAChebbi/opt/simlearner3d/Salon.hdf5" \
datamodule.masq_divider=255 \
datamodule.patch_size=512 \
datamodule.batch_size=2 \
datamodule.sign_disp_multiplier=1 \
experiment="SIMDebug" \
trainer.accelerator="cpu" \
++trainer.accumulate_grad_batches=4 \
++trainer.precision="16-mixed" \
model="msaff_model" \
++model.mode="feature" \
logger=tensorboard 
#++logger.tensorboard.experiment="test_msaff_cos_normalization_view"
