defaults:
  - augmentations: default.yaml
  - normalizations: default.yaml

# turn the config dict into ListConfig that will be fed directly to a Compose object

augmentations_list: "${oc.dict.values: datamodule.transforms.augmentations}"

# Multiple different preparations list based on the situtation : train, eval/test, or predict.
# The difference lies in the copie of some positions and in the targets processing.
normalizations_list: "${oc.dict.values: datamodule.transforms.normalizations}"
